{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <python_test_framework_demo.test_allure_report.TestLogin object at 0x0000020B06B9AE20>\n\n    @allure.story('密码缺失')\n    def test_login_failure(self):\n        with allure.step('点击用户名'):\n            print('输入用户名')\n        with allure.step('点击密码'):\n            print('输入密码')\n        print('点击登录')\n        with allure.step('点击登录之后登录失败'):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure_report.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1618287307779, "stop": 1618287307779}, {"name": "点击密码", "status": "passed", "start": 1618287307779, "stop": 1618287307779}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\TestDev\\python_test_framework_demo\\test_allure_report.py\", line 30, in test_login_failure\n    assert '1' == 1\n"}, "start": 1618287307780, "stop": 1618287307780}], "attachments": [{"name": "stdout", "source": "461d760f-a95b-43a9-8c14-b8c09c78e0ed-attachment.txt", "type": "text/plain"}], "start": 1618287307779, "stop": 1618287307780, "uuid": "a314bd6f-e7c3-44f7-aefb-ee109f02577d", "historyId": "c1be10927427fd32313eb62497ab4995", "testCaseId": "b5827c16bd98d49184544ba740c8c531", "fullName": "test_allure_report.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_allure_report"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "摩羯座"}, {"name": "thread", "value": "9464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_report"}]}