{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <python_test_framework_demo.test_allure_report.TestLogin object at 0x000002404145BB20>\n\n    @allure.story('密码缺失')\n    def test_login_failure(self):\n        with allure.step('点击用户名'):\n            print('输入用户名')\n        with allure.step('点击密码'):\n            print('输入密码')\n        print('点击登录')\n        with allure.step('点击登录之后登录失败'):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure_report.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1618287157054, "stop": 1618287157054}, {"name": "点击密码", "status": "passed", "start": 1618287157055, "stop": 1618287157055}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\TestDev\\python_test_framework_demo\\test_allure_report.py\", line 30, in test_login_failure\n    assert '1' == 1\n"}, "start": 1618287157055, "stop": 1618287157055}], "attachments": [{"name": "stdout", "source": "bada475b-d574-4191-864e-a821413ff2a4-attachment.txt", "type": "text/plain"}], "start": 1618287157054, "stop": 1618287157055, "uuid": "77ed8556-ca0c-4b2e-90b7-80760c6d6d1a", "historyId": "c1be10927427fd32313eb62497ab4995", "testCaseId": "b5827c16bd98d49184544ba740c8c531", "fullName": "test_allure_report.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_allure_report"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "摩羯座"}, {"name": "thread", "value": "9392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_report"}]}